solution for 02/05
js-tasks-ru/vue-20210511_antonio-kravets pull request #5
Opened 2021-05-21 17:57 UTC by kriffer

2021-05-21 17:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-21 18:37 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-21 19:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-21 21:11 UTC, ShGKme requested changes
Требуется небольшое исправление в 06-MeetupView

2021-05-21 21:11 UTC, ShGKme commented on 02-components/05-MeetupAgenda/index.html
> -
Этот код мешал?)

2021-05-21 21:11 UTC, ShGKme commented on 02-components/06-MeetupView/MeetupAgenda.js
> +       <meetup-agenda-item v-for="agendaItem in agenda" v-bind:key="agendaItem.id" :agenda-item="agendaItem"></meetup-agenda-item>
Принято всегда использовать сокращённую запись директив `:key="agendaItem.id"`

2021-05-21 21:11 UTC, ShGKme commented on 02-components/06-MeetupView/MeetupView.js
> +    },
Если у митапа нет изображения (imageId === null), будет некорретное изображение.

2021-05-25 16:31 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-25 16:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-25 20:15 UTC, ShGKme requested changes
В 08-MeetupsCalendar требуется обновить компонент так, чтобы не использовать шаблон в качествен реализации логики поиска митапов текущего дня. Постарайтесь при этом и не вызывать методов в шаблоне для выполнения той же операции.

Лучше подготовить вычисляемое свойство, которое сразу даст готовые для отображения данные.

2021-05-25 20:15 UTC, ShGKme commented on 02-components/08-MeetupsCalendar/MeetupsCalendar.js
>        </div>
Здесь вы шаблоном реализовали логику фильтрации митапов с поиском митапов конкретной ячейки.
Получается, что при каждом рендеринге для каждой ячейки перебираются все митапы и проверяются, а не митап ли текущей ячейки это. И также снова для следующей ячейки опять проверяются все митапы. И так при каждом ререндеринге компонента.

Это не очень оптимально и главное - это реализация логики работы внутри шаблона, где v-for+v-if используются для фильтрации данный, а не определения представления.

2021-05-26 11:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-26 11:29 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-26 13:02 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2021-05-26 13:04 UTC, merged